<p>BIZAP DATABASE HAS RECEIVED AN FUND DISBURSEMENT REQUEST FROM {{ $business_name }} OWNED BY {{ $name }}.
    THE APPLICATION HAS BEEN SUCCESSFULLY REVIEWED BY THE EDD TEAM.  PLEASE LOG INTO THE BIZAP DATABASE TO APPROVE
    THE APPLICATION REQUEST.
</p>
<p>http://bizap.dhi.bt/</p>




